### ISSUE TITLE
New issue after migration from angular 5 to 6

### ISSUE THREAD

**Issue by mraminemx** [ultratrail/generator-jhipster-leafletmap#2]
I think that the cause of my problem is the new migration from angular 5 to 6
Error : 

blog git:(master) ✗ yo jhipster-leafletmap
WARNING! This method is deprecated. Use getAllJhipsterConfig

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v5.3.4

Application files will be generated in folder: /home/vagrant/blog
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

Welcome to the JHipster leafletmap generator! v1.0.5

? Press ENTER to generate the leaflet map ! 

--- some config read from config ---
baseName=blog
packageName=org.jhipster.rscollector
clientFramework=angularX
clientPackageManager=npm
buildTool=maven

--- some function ---
angularAppName=blogApp

--- some const ---
javaDir=src/main/java/org/jhipster/rscollector/
resourceDir=src/main/resources/
webappDir=src/main/webapp/

--- variables from questions ---

message=
------

APPNAME :  Blog
Creation of the page-sets module
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: /home/vagrant/blog/.angular-cli.json doesn't exist
    at EditionInterface.module.exports [as read] (/usr/lib/node_modules/generator-jhipster-leafletmap/node_modules/mem-fs-editor/lib/actions/read.js:12:11)
    at Object.rewriteFile (/usr/lib/node_modules/generator-jhipster-leafletmap/node_modules/generator-jhipster/generators/utils.js:57:34)
    at module.exports.writing (/usr/lib/node_modules/generator-jhipster-leafletmap/generators/app/index.js:195:27)
    at Object.<anonymous> (/usr/lib/node_modules/generator-jhipster-leafletmap/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:418:27)
    at /usr/lib/node_modules/generator-jhipster-leafletmap/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/lib/node_modules/generator-jhipster-leafletmap/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/lib/node_modules/generator-jhipster-leafletmap/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)

**Comment by HugoSecteur4** [comment]
Hi,

Please update the package, it works now with Angular6.
